apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  FILE_UPLOADS_MOUNT_PATH: "/app/uploads"
  LANGFUSE_HOST: "https://cloud.langfuse.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://api:8000"

