name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    if: "${{ github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'chore: bump version to') }}"
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      BACKEND_SERVICE_ID: ${{ secrets.RAILWAY_BACKEND_SERVICE_ID }}
      FRONTEND_SERVICE_ID: ${{ secrets.RAILWAY_FRONTEND_SERVICE_ID }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Backend to Railway
        run: railway up --service=${{ env.BACKEND_SERVICE_ID }}

      - name: Deploy Frontend to Railway
        run: |
          cd frontend
          railway up --service=${{ env.FRONTEND_SERVICE_ID }}
